erp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login')
def home(request: HttpRequest):
    if request.method != 'GET':
        return HttpResponse('Not allowed', status=403)
    
    return render(request, 'erp_home.html')

urlpatterns = [
    path('', home),
    path('home', home, name='home'),
    path('admin/', admin.site.urls),
    path ('', include ('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path ('', include ('apparelManagement.urls')),
    path ('', include ('qualityControl.urls')),
    path ('', include ('marketing.urls')),
    path ('', include ('prodManagement.urls')),
]

prodManagement/urls.py
from django.urls import path
from . import views
from .services import options_service

urlpatterns = [
    path('productivity', views.Home, name = 'productivity'),

    path('productivity/operations', views.Operations, name='operations'),
    path('productivity/operation/add', views.AddOperation, name='addOperation'),
    path('productivity/operation/<int:pk>/edit', views.EditOperation, name='editOperation'),

    path('productivity/machines', views.Machines, name='machines'),
    path('productivity/machine/add', views.AddMachine, name='addMachine'),
    path('productivity/machine/<int:pk>/edit', views.EditMachine, name='editMachine'),

    path('productivity/bulletins', views.StyleBulletin, name='styleBulletins'),
    path('productivity/bulletin/add', views.AddStyleBulletin, name='addStyleBulletin'),
    path('productivity/bulletin/<int:pk>/edit', views.EditStyleBulletin, name='editStyleBulletin'),
    path('producitivty/bulletin/styles/missing', options_service.GetStylesWithoutBulletins, name='missingStylesForBulletins'),
    path('productivity/bulletin/<int:pk>/duplicate', views.DuplicateStyleBulletin, name='duplicateStyleBulletin'),
    path('productivity/bulletin/summarise', views.SummariseStyleBulletin, name='summariseSytleBulletin'),

    path('productivity/core-sheets', views.CoreSheet, name='coreSheets'),
    path('productivity/core-sheet/add', views.AddCoreSheet, name='addCoreSheet'),
    path('productivity/core-sheet/<int:workOrder>/edit', views.EditCoreSheet, name='editCoreSheet'),
    path('producitivty/core-sheet/orders/missing', options_service.GetOrdersWithMissingCS, name='missingCS'),

    path('productivity/workers', views.Workers, name='workers'),
    path('productivity/worker/add', views.AddWorker, name='addWorker'),
    path('productivity/worker/<int:pk>/edit', views.EditWorker, name='editWorker'),
    path('productivity/api/complete-group', views.MarkGroupCompletion.as_view(), name='groupCompletionAPI'),

    path('options/operations', options_service.GetOperations, name='operationsDropdown'),
    path('options/operations/sections', options_service.GetOperationSections, name='opSecs'),
    path('options/section/<int:pk>', options_service.getOperationSection, name='sectionOperation'),
    path('options/operations/categories', options_service.GetOperationCategories, name='opCats'),
    path('options/machines/types', options_service.GetMachineTypes, name='machTypes'),
    path('options/machines/manufacturers', options_service.GetMachineManufacturers, name='machManufacturers'),

    path('api/temp', views.Temp.as_view(), name='temp'),
]

prodManagement/models.py
from django.db import models
from django.contrib.auth.models import User
from apparelManagement.models import Department, StyleCard, WorkOrder

class Operation(models.Model):
    id = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=511)
    Section = models.CharField(max_length=31)
    Category = models.CharField(max_length=31)
    SkillLevel = models.PositiveIntegerField()
    SMV = models.FloatField(null=True, blank=True)
    MachineRequirement = models.BooleanField(default=False)
    MachineType = models.CharField(max_length=31)
    Rate = models.FloatField(null=True, blank=True)
    Code = models.CharField(max_length=31, blank=True, null=True)

    class Meta:
        """Meta definition for Operations."""

        indexes = [
            models.Index(fields=['Section']),
            models.Index(fields=['MachineType']),
        ]

class Machine(models.Model):
    id = models.AutoField(primary_key=True)
    MachineId = models.CharField(max_length=31)
    PurchaseDate = models.DateField(auto_now_add=True)
    Type = models.CharField(max_length=63)
    FunctionStatus = models.CharField(max_length=15)
    Manufacturer = models.CharField(max_length=15, blank=True, null=True)
    ModelNumber = models.CharField(max_length=25, null=True, blank=True)
    SerialNumber = models.CharField(max_length=15, null=True, blank=True)
    Department = models.ForeignKey(Department, on_delete=models.PROTECT, blank=True, null=True)

    class Meta:
        """Meta definition for Machines."""

        indexes = [
            models.Index(fields=['FunctionStatus', 'Department'])
        ]

class StyleBulletin(models.Model):
    id = models.AutoField(primary_key=True)
    StyleCard = models.ForeignKey(StyleCard, on_delete=models.PROTECT)

    class Meta:
        """Meta definition for Style Bulletin."""
        indexes = [
            models.Index(fields=['StyleCard'])
        ]

class StyleBulletinOperation(models.Model):
    id = models.AutoField(primary_key=True)
    StyleBulletin = models.ForeignKey(StyleBulletin, on_delete=models.CASCADE)
    Sequence = models.PositiveIntegerField()
    Operation = models.ForeignKey(Operation, on_delete=models.PROTECT)
    Section = models.CharField(max_length=31)
    IsStart = models.BooleanField(default=False)
    IsEnd = models.BooleanField(default=False)

    class Meta:
        """Meta definition for Style Bulletin Operation."""
        indexes = [
            models.Index(fields=['StyleBulletin']),
            models.Index(fields=['Operation']),
            models.Index(fields=['Section']),
        ]

class Cut(models.Model):
    id = models.AutoField(primary_key=True)
    WorkOrder = models.ForeignKey(WorkOrder, on_delete=models.PROTECT)
    Shade = models.CharField(max_length=31)
    WarpShrinkage = models.FloatField()
    WeftShrinkage = models.FloatField()
    Inseam = models.CharField(max_length=31, null=True, blank=True)
    NoOfPlies = models.PositiveIntegerField()
    CutNumber = models.PositiveIntegerField()

    class Meta:
        indexes = [
            models.Index(fields=['WorkOrder']),
        ]

class Bundle(models.Model):
    id =  models.AutoField(primary_key=True)
    Cut = models.ForeignKey(Cut, on_delete=models.CASCADE)
    Size = models.CharField(max_length=31)
    Bundle = models.PositiveIntegerField()

    class Meta:
        indexes = [
            models.Index(fields=['Cut']),
            models.Index(fields=['Size']),
        ]

class Worker(models.Model):
    WorkerCode = models.PositiveBigIntegerField(primary_key=True)
    WorkerName = models.CharField(max_length=255)
    FatherSpouseName = models.CharField(max_length=255, blank=True, null=True)
    Department = models.ForeignKey(Department, on_delete=models.PROTECT, blank=True, null=True)
    SubDepartment = models.CharField(max_length=31, blank=True, null=True)
    CNIC = models.CharField(max_length=255, blank=True, null=True)
    DateOfBirth = models.DateField(blank=True, null=True)
    DateOfJoining = models.DateField(blank=True, null=True, auto_now_add=True)
    Status = models.CharField(max_length=31)
    Gender = models.CharField(max_length=7)
    User = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True)

    class Meta:
        indexes = [
            models.Index(fields=['Department']),
            models.Index(fields=['Status']),
        ]

class RFIDCard(models.Model):
    CardId = models.PositiveBigIntegerField(primary_key=True)
    CardNumber = models.PositiveBigIntegerField(unique=True)
    GroupNumber = models.PositiveBigIntegerField()
    GroupStatus = models.CharField(max_length=31, default='InComplete')

    class Meta:
        indexes = [
            models.Index(fields=['GroupNumber']),
            models.Index(fields=['GroupStatus']),
        ]

prodManagement/templates/operations/add.html
{% extends 'prodManagement/base.html' %}

{% block title %}
    Operation Addition
{% endblock title %}

{% block content %}
    <form method="POST" id="operationForm" autocomplete="off">
        {% csrf_token %}          <!--This is to protect against CSRF attacks-->
        <div class="{{theme.border}}">
            <div class="grid grid-cols-4 my-2 {{theme.justify}} {{theme.align}}">
                <div class="flex col-[1/3] items-center">
                    <label class="mx-2 whitespace-nowrap">Name:&nbsp; </label>
                    <input type="text" class="flex-grow {{theme.textInput}}" name="Name" required>
                </div>
                <div class="flex col-[3/4] items-center">
                    <label class="mx-2 whitespace-nowrap">Secton:&nbsp; </label>
                    <select id="id_Section" class="{{theme.dropdown}}" name="Section" required> </select>
                </div>
                <div class="flex col-[4/5] items-center">
                    <label class="mx-2 whitespace-nowrap">Category:&nbsp; </label>
                    <select id="id_Category" class="{{theme.dropdown}}" name="Category" required> </select>
                </div>
            </div>
            <div class="grid grid-cols-4 my-2 {{theme.justify}} {{theme.align}}">
                <div class="flex col-[1/2] items-center">
                    <label class="mx-2 whitespace-nowrap">Level:&nbsp; </label>
                    <select class="{{theme.dropdown}}" name="Level" required>
                        {% for i in "1234" %}
                            <option value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="flex col-[2/3] items-center">
                    <label class="mx-2 whitespace-nowrap">SAM:&nbsp; </label>
                    <input type="number" min="0" step="any" class="flex-grow {{theme.textInput}}" name="SMV" required>
                </div>
                <div class="flex col-[3/4] items-center">
                    <label class="mx-2 whitespace-nowrap">Rate:&nbsp; </label>
                    <input type="number" min="0" step="any" class="flex-grow {{theme.textInput}}" name="Rate" required>
                </div>
                <div class="flex col-[4/5] items-center">
                    <label class="mx-2 whitespace-nowrap">Code:&nbsp; </label>
                    <input type="text" class="flex-grow {{theme.textInput}}" name="Code">
                </div>
            </div>
            <div class="grid grid-cols-4 my-2 {{theme.justify}} {{theme.align}}">
                <div class="flex col-[1/4] items-center">
                    <label class="mx-2 whitespace-nowrap">Type:&nbsp; </label>
                    <select id="id_Type" class="{{theme.dropdown}}" name="Type" required> </select>
                </div>
                <div class="flex col-[4/5] items-center">
                    <button type="submit" class="{{theme.buttonBasic}} mx-2" >Save</button>
                </div>
            </div>
        </div>
    </form>

    <script> //To run when the page loads
        window.addEventListener('load', async () => {
            showLoadingIcon();

            let response = await fetch(`{% url 'opSecs' %}`);
            const sections = await response.json();
            await appendOptions('id_Section', sections);

            response = await fetch(`{% url 'opCats' %}`);
            const operationCategories = await response.json();
            await appendOptions('id_Category', operationCategories);

            response = await fetch(`{% url 'machTypes' %}`);
            const machineTypes = await response.json();
            await appendOptions('id_Type', machineTypes);

            hideLoadingIcon();
        });
    </script>
{% endblock content %}

prodManagement/templates/operations/edit.html
{% extends 'prodManagement/base.html' %}

{% block title %}
    Editing Operation
{% endblock title %}

{% block content %}
    <form method="POST" id="operationForm" autocomplete="off">
        {% csrf_token %}          <!--This is to protect against CSRF attacks-->
        <div class="{{theme.border}}">
            <div class="grid grid-cols-4 my-2 {{theme.justify}} {{theme.align}}">
                <div class="flex col-[1/3] items-center">
                    <label class="mx-2 whitespace-nowrap">Name:&nbsp; </label>
                    <input type="text" class="flex-grow {{theme.textInput}}" name="Name" value="{{data.Name}}" required>
                </div>
                <div class="flex col-[3/4] items-center">
                    <label class="mx-2 whitespace-nowrap">Secton:&nbsp; </label>
                    <select id="id_Section" class="{{theme.dropdown}}" name="Section" required> </select>
                </div>
                <div class="flex col-[4/5] items-center">
                    <label class="mx-2 whitespace-nowrap">Category:&nbsp; </label>
                    <select id="id_Category" class="{{theme.dropdown}}" name="Category" required> </select>
                </div>
            </div>
            <div class="grid grid-cols-4 my-2 {{theme.justify}} {{theme.align}}">
                <div class="flex col-[1/2] items-center">
                    <label class="mx-2 whitespace-nowrap">Level:&nbsp; </label>
                    <select class="{{theme.dropdown}}" name="Level" required>
                        {% for i in "1234" %}
                            <option value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="flex col-[2/3] items-center">
                    <label class="mx-2 whitespace-nowrap">SAM:&nbsp; </label>
                    <input type="number" min="0" step="any" class="flex-grow {{theme.textInput}}" name="SMV" value="{{data.SMV}}" required>
                </div>
                <div class="flex col-[3/4] items-center">
                    <label class="mx-2 whitespace-nowrap">Rate:&nbsp; </label>
                    <input type="number" min="0" step="any" class="flex-grow {{theme.textInput}}" name="Rate" value="{{data.Rate}}" required>
                </div>
                <div class="flex col-[4/5] items-center">
                    <label class="mx-2 whitespace-nowrap">Code:&nbsp; </label>
                    <input type="text" class="flex-grow {{theme.textInput}}" name="Code" value="{{data.Code}}">
                </div>
            </div>
            <div class="grid grid-cols-4 my-2 {{theme.justify}} {{theme.align}}">
                <div class="flex col-[1/4] items-center">
                    <label class="mx-2 whitespace-nowrap">Type:&nbsp; </label>
                    <select id="id_Type" class="{{theme.dropdown}}" name="Type" required> </select>
                </div>
                <div class="flex col-[4/5] items-center">
                    <button type="submit" class="{{theme.buttonBasic}} mx-2" >Save</button>
                </div>
            </div>
        </div>
    </form>

    <script> //To run when the page loads
        window.addEventListener('load', async () => {
            showLoadingIcon();

            let response = await fetch(`{% url 'opSecs' %}`);
            const sections = await response.json();
            await appendOptions('id_Section', sections, '{{data.Section}}');

            response = await fetch(`{% url 'opCats' %}`);
            const operationCategories = await response.json();
            await appendOptions('id_Category', operationCategories, '{{data.Category}}');

            response = await fetch(`{% url 'machTypes' %}`);
            const machineTypes = await response.json();
            await appendOptions('id_Type', machineTypes, '{{data.MachineType}}');

            hideLoadingIcon();
        });
    </script>
{% endblock content %}

prodManagement/templates/operations/home.html
{% extends 'prodManagement/base.html' %}

{% block title %}
    Operations Bank
{% endblock title %}

{% block content %}
    <div class="{{theme.border}}">
        <form action="{% url 'operations' %}" method="get" autocomplete="off">
            <div class="grid grid-cols-10 {{theme.justify}} {{theme.align}}">
                <div class="flex flex-col col-[1/3] items-center">
                    <span class="text-sm text-gray-500 mb-1">Search:</span>
                    <input class="{{theme.textInput}}" name="search" value="{{search}}" placeholder="">
                </div>
                <div class="flex flex-col col-[3/5] items-center">
                    <span class="text-sm text-gray-500 mb-1">Section:</span>
                    <select name="sectionFilter" class="{{theme.dropdown}}" id="section" onchange="this.form.submit()"></select>
                </div>
                <div class="flex flex-col col-[5/6] items-center">
                    <span class="text-sm text-gray-500 mb-1">Skill Level:</span>
                    <select name="skillLevel" class="{{theme.dropdown}}" id="skillLevel" onchange="this.form.submit()">
                        <option value="null">All</option>
                        {% for i in "1234" %}
                            <option value="{{ i }}" {% if skillLevel == i %} selected {% endif %}
                                >{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="flex flex-col col-[6/8] items-center">
                    <span class="text-sm text-gray-500 mb-1">Machine Type:</span>
                    <select name="machineType" class="{{theme.dropdown}}" id="machineType" onchange="this.form.submit()"></select>
                </div>
                <div class="flex flex-col col-[8/9] items-center">
                    <span class="text-sm text-gray-500 mb-1">Min Rate/SAM:</span>
                    <input type="number" min="0" class="{{theme.textInput}}" name="ratePerSAM" value="{{ratePerSAM}}" placeholder="">
                </div>
                <div class="flex col-[9/11] btn-group {{theme.align}} justify-end ml-1">
                    <button type="submit" class="{{theme.buttonBasic}}">Search</button>
                    <a class="{{theme.buttonBasic}}" href="{% url 'addOperation' %}" role="button">Add</a>
                </div>
            </div>
        </form>
    </div>

    <div id="operationTable" class="mt-6">
        <table class="{{theme.table}}">
            <tr class = "{{theme.tableHead}}">
                <th scope="col">Code</th>
                <th scope="col">Name</th>
                <th scope="col">Section</th>
                <th scope="col">Category</th>
                <th scope="col">Level</th>
                <th scope="col">Type</th>
                <th scope="col">SAM</th>
                <th scope="col">Rate</th>
            </tr>
            <tbody id="tableData" class = "{{theme.tableBody}}">
                {% for data in operations%}
                <tr class="{{theme.tableBodyRow}}">
                    <td class="{{theme.hyperLink}}"> <a href="{% url 'editOperation' pk=data.id %}">{{ data.id }}</a></td>
                    <td>{{ data.Name }}</td>
                    <td>{{ data.Section }}</td>
                    <td>{{ data.Category }}</td>
                    <td>{{ data.SkillLevel }}</td>
                    <td>{{ data.MachineType }}</td>
                    <td>{{ data.SMV }}</td>
                    <td>{{ data.Rate }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="{{ theme.pagination }}">
        <div class="btn-group">
            {% if page_obj.has_previous %}
                <a href="?page=1&search={{search}}&sectionFilter={{sectionFilter}}&skillLevel={{skillLevel}}&machineType={{machineType}}&ratePerSAM={{ratePerSAM}}" class="btn btn-sm">First</a>
                <a href="?page={{ page_obj.previous_page_number }}&search={{search}}&sectionFilter={{sectionFilter}}&skillLevel={{skillLevel}}&machineType={{machineType}}&ratePerSAM={{ratePerSAM}}" class="btn btn-sm">Previous</a>
            {% else %}
                <button class="btn btn-sm" disabled>First</button>
                <button class="btn btn-sm" disabled>Previous</button>
            {% endif %}
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&search={{search}}&sectionFilter={{sectionFilter}}&skillLevel={{skillLevel}}&machineType={{machineType}}&ratePerSAM={{ratePerSAM}}" class="btn btn-sm">Next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}&search={{search}}&sectionFilter={{sectionFilter}}&skillLevel={{skillLevel}}&machineType={{machineType}}&ratePerSAM={{ratePerSAM}}" class="btn btn-sm">Last</a>
            {% else %}
                <button class="btn btn-sm" disabled>Next</button>
                <button class="btn btn-sm" disabled>Last</button>
            {% endif %}
        </div>
    </div>

    <script> //To run when the page loads
        window.addEventListener('load', async () => {
            showLoadingIcon();

            let response = await fetch('/options/operations/sections');
            const sections = await response.json();
            await appendOptions('section', sections, '{{sectionFilter}}');

            response = await fetch('/options/machines/types');
            const machineTypes = await response.json();
            await appendOptions('machineType', machineTypes, '{{machineType}}');

            hideLoadingIcon();
        });
    </script>
{% endblock content %}