erp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login')
def home(request: HttpRequest):
    if request.method != 'GET':
        return HttpResponse('Not allowed', status=403)
    
    return render(request, 'erp_home.html')

urlpatterns = [
    path('', home),
    path('home', home, name='home'),
    path('admin/', admin.site.urls),
    path ('', include ('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path ('', include ('apparelManagement.urls')),
    path ('', include ('qualityControl.urls')),
    path ('', include ('marketing.urls')),
    path ('', include ('prodManagement.urls')),
]

prodManagement/urls.py
from django.urls import path
from . import views
from .services import options_service

urlpatterns = [
    path('productivity', views.Home, name = 'productivity'),

    path('productivity/operations', views.Operations, name='operations'),
    path('productivity/operation/add', views.AddOperation, name='addOperation'),
    path('productivity/operation/<int:pk>/edit', views.EditOperation, name='editOperation'),

    path('productivity/machines', views.Machines, name='machines'),
    path('productivity/machine/add', views.AddMachine, name='addMachine'),
    path('productivity/machine/<int:pk>/edit', views.EditMachine, name='editMachine'),

    path('productivity/bulletins', views.StyleBulletin, name='styleBulletins'),
    path('productivity/bulletin/add', views.AddStyleBulletin, name='addStyleBulletin'),
    path('productivity/bulletin/<int:pk>/edit', views.EditStyleBulletin, name='editStyleBulletin'),
    path('producitivty/bulletin/styles/missing', options_service.GetStylesWithoutBulletins, name='missingStylesForBulletins'),
    path('productivity/bulletin/<int:pk>/duplicate', views.DuplicateStyleBulletin, name='duplicateStyleBulletin'),
    path('productivity/bulletin/summarise', views.SummariseStyleBulletin, name='summariseSytleBulletin'),

    path('productivity/core-sheets', views.CoreSheet, name='coreSheets'),
    path('productivity/core-sheet/add', views.AddCoreSheet, name='addCoreSheet'),
    path('productivity/core-sheet/<int:workOrder>/edit', views.EditCoreSheet, name='editCoreSheet'),
    path('producitivty/core-sheet/orders/missing', options_service.GetOrdersWithMissingCS, name='missingCS'),

    path('productivity/workers', views.Workers, name='workers'),
    path('productivity/worker/add', views.AddWorker, name='addWorker'),
    path('productivity/worker/<int:pk>/edit', views.EditWorker, name='editWorker'),
    path('productivity/api/complete-group', views.MarkGroupCompletion.as_view(), name='groupCompletionAPI'),

    path('options/operations', options_service.GetOperations, name='operationsDropdown'),
    path('options/operations/sections', options_service.GetOperationSections, name='opSecs'),
    path('options/section/<int:pk>', options_service.getOperationSection, name='sectionOperation'),
    path('options/operations/categories', options_service.GetOperationCategories, name='opCats'),
    path('options/machines/types', options_service.GetMachineTypes, name='machTypes'),
    path('options/machines/manufacturers', options_service.GetMachineManufacturers, name='machManufacturers'),

    path('api/temp', views.Temp.as_view(), name='temp'),
]

prodManagement/models.py
from django.db import models
from django.contrib.auth.models import User
from apparelManagement.models import Department, StyleCard, WorkOrder

class Operation(models.Model):
    id = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=511)
    Section = models.CharField(max_length=31)
    Category = models.CharField(max_length=31)
    SkillLevel = models.PositiveIntegerField()
    SMV = models.FloatField(null=True, blank=True)
    MachineRequirement = models.BooleanField(default=False)
    MachineType = models.CharField(max_length=31)
    Rate = models.FloatField(null=True, blank=True)
    Code = models.CharField(max_length=31, blank=True, null=True)

    class Meta:
        """Meta definition for Operations."""

        indexes = [
            models.Index(fields=['Section']),
            models.Index(fields=['MachineType']),
        ]

class Machine(models.Model):
    id = models.AutoField(primary_key=True)
    MachineId = models.CharField(max_length=31)
    PurchaseDate = models.DateField(auto_now_add=True)
    Type = models.CharField(max_length=63)
    FunctionStatus = models.CharField(max_length=15)
    Manufacturer = models.CharField(max_length=15, blank=True, null=True)
    ModelNumber = models.CharField(max_length=25, null=True, blank=True)
    SerialNumber = models.CharField(max_length=15, null=True, blank=True)
    Department = models.ForeignKey(Department, on_delete=models.PROTECT, blank=True, null=True)

    class Meta:
        """Meta definition for Machines."""

        indexes = [
            models.Index(fields=['FunctionStatus', 'Department'])
        ]

class StyleBulletin(models.Model):
    id = models.AutoField(primary_key=True)
    StyleCard = models.ForeignKey(StyleCard, on_delete=models.PROTECT)

    class Meta:
        """Meta definition for Style Bulletin."""
        indexes = [
            models.Index(fields=['StyleCard'])
        ]

class StyleBulletinOperation(models.Model):
    id = models.AutoField(primary_key=True)
    StyleBulletin = models.ForeignKey(StyleBulletin, on_delete=models.CASCADE)
    Sequence = models.PositiveIntegerField()
    Operation = models.ForeignKey(Operation, on_delete=models.PROTECT)
    Section = models.CharField(max_length=31)
    IsStart = models.BooleanField(default=False)
    IsEnd = models.BooleanField(default=False)

    class Meta:
        """Meta definition for Style Bulletin Operation."""
        indexes = [
            models.Index(fields=['StyleBulletin']),
            models.Index(fields=['Operation']),
            models.Index(fields=['Section']),
        ]

class Cut(models.Model):
    id = models.AutoField(primary_key=True)
    WorkOrder = models.ForeignKey(WorkOrder, on_delete=models.PROTECT)
    Shade = models.CharField(max_length=31)
    WarpShrinkage = models.FloatField()
    WeftShrinkage = models.FloatField()
    Inseam = models.CharField(max_length=31, null=True, blank=True)
    NoOfPlies = models.PositiveIntegerField()
    CutNumber = models.PositiveIntegerField()

    class Meta:
        indexes = [
            models.Index(fields=['WorkOrder']),
        ]

class Bundle(models.Model):
    id =  models.AutoField(primary_key=True)
    Cut = models.ForeignKey(Cut, on_delete=models.CASCADE)
    Size = models.CharField(max_length=31)
    Bundle = models.PositiveIntegerField()

    class Meta:
        indexes = [
            models.Index(fields=['Cut']),
            models.Index(fields=['Size']),
        ]

class Worker(models.Model):
    WorkerCode = models.PositiveBigIntegerField(primary_key=True)
    WorkerName = models.CharField(max_length=255)
    FatherSpouseName = models.CharField(max_length=255, blank=True, null=True)
    Department = models.ForeignKey(Department, on_delete=models.PROTECT, blank=True, null=True)
    SubDepartment = models.CharField(max_length=31, blank=True, null=True)
    CNIC = models.CharField(max_length=255, blank=True, null=True)
    DateOfBirth = models.DateField(blank=True, null=True)
    DateOfJoining = models.DateField(blank=True, null=True, auto_now_add=True)
    Status = models.CharField(max_length=31)
    Gender = models.CharField(max_length=7)
    User = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True)

    class Meta:
        indexes = [
            models.Index(fields=['Department']),
            models.Index(fields=['Status']),
        ]

class RFIDCard(models.Model):
    CardId = models.PositiveBigIntegerField(primary_key=True)
    CardNumber = models.PositiveBigIntegerField(unique=True)
    GroupNumber = models.PositiveBigIntegerField()
    GroupStatus = models.CharField(max_length=31, default='InComplete')

    class Meta:
        indexes = [
            models.Index(fields=['GroupNumber']),
            models.Index(fields=['GroupStatus']),
        ]

prodManagement/templates/machines/add.html
{% extends 'prodManagement/base.html' %}

{% block title %}
    Machines Addition
{% endblock title %}

{% block content %}
    <form method="POST" id="machineForm" autocomplete="off">
        {% csrf_token %}          <!--This is to protect against CSRF attacks-->
        <div class="{{theme.border}}">
            <div class="grid grid-cols-4 my-2 {{theme.justify}} {{theme.align}}">
                <div class="flex col-[1/2] items-center">
                    <label class="mx-2 whitespace-nowrap">Machine Id:&nbsp; </label>
                    <input type="text" class="flex-grow {{theme.textInput}}" name="MachineId" required>
                </div>
                <div class="flex col-[2/3] items-center">
                    <label class="mx-2 whitespace-nowrap">Machine Type:&nbsp; </label>
                    <select id="id_Type" class="{{theme.dropdown}}" name="Type" required> </select>
                </div>
                <div class="flex col-[3/4] items-center">
                    <label class="mx-2 whitespace-nowrap">Functioning?&nbsp; </label>
                    <select id="id_Status" class="{{theme.dropdown}}" name="FunctionStatus" required>
                        <option value="null">--------</option>
                        <option value="Yes">Yes</option>
                        <option value="No">No</option>
                        <option value="Sold">Sold</option>
                        <option value="Dead">Dead</option>
                    </select>
                </div>
                <div class="flex col-[4/5] items-center">
                    <label class="mx-2 whitespace-nowrap">Manufacturer:&nbsp; </label>
                    <select id="id_Manufacturer" class="{{theme.dropdown}}" name="Manufacturer" required> </select>    
                </div>
            </div>
            <div class="grid grid-cols-4 my-2 {{theme.justify}} {{theme.align}}">
                <div class="flex col-[1/2] items-center">
                    <label class="mx-2 whitespace-nowrap">Model Number:&nbsp; </label>
                    <input type="text" class="flex-grow {{theme.textInput}}" name="ModelNumber">
                </div>
                <div class="flex col-[2/3] items-center">
                    <label class="mx-2 whitespace-nowrap">Serial Number:&nbsp; </label>
                    <input type="text" class="flex-grow {{theme.textInput}}" name="SerialNumber">
                </div>
                <div class="flex col-[3/4] items-center">
                    <label class="mx-2 whitespace-nowrap">Department:&nbsp; </label>
                    <select id="id_Department" class="{{theme.dropdown}}" name="Department"> </select>    
                </div>
                <div class="flex col-[4/5] items-center">
                    <button type="submit" class="{{theme.buttonBasic}} mx-2" >Save</button>
                </div>
            </div>
        </div>
    </form>

    <script>    //This script runs after page is loaded
        window.addEventListener('load', async () => {
            showLoadingIcon();

            let response = await fetch('/options/machines/types');
            const machineTypes = await response.json();
            await appendOptions('id_Type', machineTypes);

            response = await fetch('/options/machines/manufacturers');
            const manufacturers = await response.json();
            await appendOptions('id_Manufacturer', manufacturers);

            response = await fetch('/options/departments');
            const departments = await response.json();
            await appendOptions('id_Department', departments);

            hideLoadingIcon();
        });
    </script>
{% endblock content %}

prodManagement/templates/machines/edit.html
{% extends 'prodManagement/base.html' %}

{% block title %}
    Updating Machine
{% endblock title %}

{% block content %}
    <form method="POST" id="operationForm" autocomplete="off">
        {% csrf_token %}          <!--This is to protect against CSRF attacks-->
        <div class="{{theme.border}}">
            <div class="grid grid-cols-4 my-2 {{theme.justify}} {{theme.align}}">
                <div class="flex col-[1/2] items-center">
                    <label class="mx-2 whitespace-nowrap">Machine Id:&nbsp; </label>
                    <input type="text" class="flex-grow {{theme.textInput}}" name="MachineId" value="{{data.MachineId}}" required>
                </div>
                <div class="flex col-[2/3] items-center">
                    <label class="mx-2 whitespace-nowrap">Machine Type:&nbsp; </label>
                    <select id="id_Type" class="{{theme.dropdown}}" name="Type" required> </select>
                </div>
                <div class="flex col-[3/4] items-center">
                    <label class="mx-2 whitespace-nowrap">Functioning?&nbsp; </label>
                    <select id="id_Status" class="{{theme.dropdown}}" name="FunctionStatus" required>
                        <option value="Yes" {% if data.FunctionStatus == 'Yes' %} selected {% endif %}>Yes</option>
                        <option value="No" {% if data.FunctionStatus == 'No' %} selected {% endif %}>No</option>
                        <option value="Sold" {% if data.FunctionStatus == 'Sold' %} selected {% endif %}>Sold</option>
                        <option value="Dead" {% if data.FunctionStatus == 'Dead' %} selected {% endif %}>Dead</option>
                    </select>
                </div>
                <div class="flex col-[4/5] items-center">
                    <label class="mx-2 whitespace-nowrap">Manufacturer:&nbsp; </label>
                    <select id="id_Manufacturer" class="{{theme.dropdown}}" name="Manufacturer" required> </select>    
                </div>
            </div>
            <div class="grid grid-cols-4 my-2 {{theme.justify}} {{theme.align}}">
                <div class="flex col-[1/2] items-center">
                    <label class="mx-2 whitespace-nowrap">Model Number:&nbsp; </label>
                    <input type="text" class="flex-grow {{theme.textInput}}" name="ModelNumber" value="{{data.ModelNumber}}">
                </div>
                <div class="flex col-[2/3] items-center">
                    <label class="mx-2 whitespace-nowrap">Serial Number:&nbsp; </label>
                    <input type="text" class="flex-grow {{theme.textInput}}" name="SerialNumber" value="{{data.SerialNumber}}">
                </div>
                <div class="flex col-[3/4] items-center">
                    <label class="mx-2 whitespace-nowrap">Department:&nbsp; </label>
                    <select id="id_Department" class="{{theme.dropdown}}" name="Department"> </select>    
                </div>
                <div class="flex col-[4/5] items-center">
                    <button type="submit" class="{{theme.buttonBasic}} mx-2" >Save</button>
                </div>
            </div>
        </div>
    </form>

    <script>    //This script runs after page is loaded
        window.addEventListener('load', async () => {
            showLoadingIcon();

            let response = await fetch('/options/machines/types');
            const machineTypes = await response.json();
            await appendOptions('id_Type', machineTypes, '{{data.Type}}');

            response = await fetch('/options/machines/manufacturers');
            const manufacturers = await response.json();
            await appendOptions('id_Manufacturer', manufacturers, '{{data.Manufacturer}}');

            response = await fetch('/options/departments');
            const departments = await response.json();
            await appendOptions('id_Department', departments, '{{data.Department}}');

            hideLoadingIcon();
        });
    </script>
{% endblock content %}

prodManagement/templates/machines/home.html
{% extends 'prodManagement/base.html' %}

{% block title %}
    Machines
{% endblock title %}

{% block content %}
    <div class="{{theme.border}}">
        <form action="{% url 'machines' %}" method="get" autocomplete="off">
            <div class="grid grid-cols-12 {{theme.justify}} {{theme.align}}">
                <div class="flex flex-col col-[1/3] items-center">
                    <span class="text-sm text-gray-500 mb-1">Search:</span>
                    <input class="{{theme.textInput}}" name="search" value="{{search}}" placeholder="">
                </div>
                <div class="flex flex-col col-[3/5] items-center">
                    <span class="text-sm text-gray-500 mb-1">Type:</span>
                    <select name="type" class="{{theme.dropdown}}" id="type" onchange="this.form.submit()"></select>
                </div>
                <div class="flex flex-col col-[5/7] items-center">
                    <span class="text-sm text-gray-500 mb-1">Working?</span>
                    <select name="status" class="{{theme.dropdown}}" id="status" onchange="this.form.submit()">
                        <option value="null" {% if status == None %} selected {% endif %}>--------</option>
                        <option value="Yes" {% if status == 'Yes' %} selected {% endif %}>Yes</option>
                        <option value="No" {% if status == 'No' %} selected {% endif %}>No</option>
                        <option value="Sold" {% if status == 'Sold' %} selected {% endif %}>Sold</option>
                        <option value="Dead" {% if status == 'Dead' %} selected {% endif %}>Dead</option>
                    </select>
                </div>
                <div class="flex flex-col col-[7/9] items-center">
                    <span class="text-sm text-gray-500 mb-1">Manufacturer:</span>
                    <select name="manufacturer" class="{{theme.dropdown}}" id="manufacturer" onchange="this.form.submit()"></select>
                </div>
                <div class="flex flex-col col-[9/11] items-center">
                    <span class="text-sm text-gray-500 mb-1">Department:</span>
                    <select name="department" class="{{theme.dropdown}}" id="department" onchange="this.form.submit()">
                    </select>
                </div>
                <div class="flex col-[11/13] btn-group {{theme.align}} justify-end ml-1">
                    <button type="submit" class="{{theme.buttonBasic}}">Search</button>
                    <a class="{{theme.buttonBasic}}" href="{% url 'addMachine' %}" role="button">Add</a>
                </div>
            </div>
        </form>
    </div>

    <div id="operationTable" class="mt-6">
        <table class="{{theme.table}}">
            <tr class = "{{theme.tableHead}}">
                <th scope="col">Number</th>
                <th scope="col">Id</th>
                <th scope="col">Type</th>
                <th scope="col">Functioning?</th>
                <th scope="col">Manufacturer</th>
                <th scope="col">Model</th>
                <th scope="col">Serial</th>
                <th scope="col">Department</th>
            </tr>
            <tbody id="tableData" class = "{{theme.tableBody}}">
                {% for data in machines %}
                    <tr class="{{theme.tableBodyRow}}">
                        <td class="{{theme.hyperLink}}"><a href="{% url 'editMachine' pk=data.id %}">{{ data.id }}</a></td>
                        <td>{{ data.MachineId }}</td>
                        <td>{{ data.Type }}</td>
                        <td>{{ data.FunctionStatus }}</td>
                        <td>{{ data.Manufacturer }}</td>
                        <td>{{ data.ModelNumber }}</td>
                        <td>{{ data.SerialNumber }}</td>
                        <td>{{ data.Department }}</td>
                    </tr>
                {% endfor %}    
            </tbody>
        </table>
    </div>

    <script> //To run when the page loads
        window.addEventListener('load', async () => {
            showLoadingIcon();

            let response = await fetch('/options/machines/types');
            const machineTypes = await response.json();
            await appendOptions('type', machineTypes, '{{type}}');

            response = await fetch('/options/machines/manufacturers');
            const machineManufacturers = await response.json();
            await appendOptions('manufacturer', machineManufacturers, '{{manufacturer}}');

            response = await fetch('/options/departments');
            const departments = await response.json();
            await appendOptions('department', departments, '{{department}}');

            hideLoadingIcon();
        });
    </script>
{% endblock content %}